### ISSUE TITLE
Separating of Flash processes per Window

### ISSUE THREAD

**Issue by cngc4e** [Cassolette/Transformice-Electron#3]
Unfortunately, Electrons seems to share the same flash process for all windows. This makes the game very laggy when multiple windows are open.

A few ways I can think of to solve it:
1. Start a new electron app instance for each game. Pros: less headache upstream. Cons: Incompatibility with existing packagers; more resources allocated for each V8 instance.
2. Ship custom Electron app with Flash patches. Pros: Less memory consumption; Access to lower level stuff. Cons: Headache; Upstreaming/maintenance issues.

**Comment by Cassolette** [comment]
Resolved by 762952d339f2446633f9c2924fb49fe421cbd893, creating a new app instance for each window.

The option to fork Electron is still open, as a regression has occurred – starting up the 2nd instance and above takes really long (up to 12s at times).
